### ISSUE TITLE
Use high contrast mode color keywords

### ISSUE THREAD

**Issue by ericwbailey** [enatario/SCSS-Base#1]
Lil' nitpick: https://github.com/enatario/SCSS-Base/blob/master/scss/base/_media.scss#L13

You'll want to use one of the following to adhere to the HCM theme. This will ensure it'll update dynamically to always be visible:

- windowText
- highlightText
- highlight
- buttonFace
- window

Happy to help you test if you want :)

**Comment by enatario** [comment]
Yes! Can you issue a PR? :)

**Comment by ericwbailey** [comment]
No problemo!

**Comment by ericwbailey** [comment]
Here ya go! https://github.com/enatario/SCSS-Base/pull/2
